### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by bihor** [4wdmedia/vierwd_linkhandler#1]
I have tested the extension with the given example in TYPO3 8.7.12, but I get this error:

> Fatal error: Declaration of Vierwd\VierwdLinkHandler\StaticLinkHandler::getBodyTagAttributes() must be compatible with Vierwd\VierwdLinkHandler\AbstractLinkHandler::getBodyTagAttributes(): array in /var/www/html/typo3conf/ext/vierwd_linkhandler/Classes/StaticLinkHandler.php on line 0

It would be nice too, if you would explain the example.

**Comment by rvock** [comment]
Thanks for the report. I could not reproduce this bug with our setup, but I think we have a different setting of error_reporting or a different PHP Version.
Nonetheless, the declaration of those methods were different. So I changed the declaration of our AbstractLinkHandler to be compatible with the LinkHandlerInterface.

Could you test the current master and confirm the bug is fixed?

**Comment by bihor** [comment]
Yes, it works now and I  understand it now.
